### ISSUE TITLE
Slideshow

### ISSUE THREAD

**Issue by liubaixue** [liubaixue/aaronsage#20]
### Tasks
- [ ] add arrows
- [ ] arrows loop slide series
- [ ] left arrow goes backwards in series
- [ ] right arrow goes forward in series
