### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by liubaixue** [liubaixue/aaronsage#21]
### Tasks
- [ ] create about page
- [ ] place page as the last side in series
- [ ] link page to 'about' svg
- [ ] add placeholder img
